# 错误处理

> 每当在正在验证的数据中发现错误时，pydantic 都会引发 ValidationError。

异常的方法：

| 方法         | 描述                           |
| ------------ | ------------------------------ |
| `e.errors()` | 返回输入数据中发现的错误的列表 |
| `e.json()`   | 返回一个表示 errors 的 JSON    |
| `str(e)`     | 返回人类可读的错误表示         |

异常的属性：

| 属性   | 描述                                                                                                     |
| ------ | -------------------------------------------------------------------------------------------------------- |
| `loc`  | 错误的位置列表。列表中的第一项将是发生错误的字段，如果该字段是子模型，则将出现后续项以指示错误的嵌套位置 |
| `type` | 计算机可读的错误类型的标识符                                                                             |
| `msg`  | 人类可读的错误解释                                                                                       |
| `ctx`  | 包含呈现错误消息所需的值的可选对象                                                                       |